stages:
  data_prep:
    cmd: python src/data_prep.py
    deps:
    - src/data_prep.py
    - data/raw/telco_churn.csv
    outs:
    - data/processed/telco_churn_processed.csv

  train:
    cmd: conda run -n pycaret-env python src/train.py
    deps:
    - src/train.py
    - data/processed/telco_churn_processed.csv
    - params.yaml

  evaluate:
    cmd: conda run -n pycaret-env python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/processed/telco_churn_processed.csv

    ## Stages completos
